export type Category = 'GST' | 'TDS/TCS' | 'Income Tax' | 'ROC/MCA' | 'ESI/PF'

export type EntityType = 'Pvt Ltd' | 'LLP' | 'Partnership' | 'Proprietorship'

export interface ComplianceItem {
  name: string
  form?: string
  dueDate: string
  dueDateDay: number
  entities: EntityType[]
  category: Category
  penalty: string
  note?: string
}

export interface MonthData {
  month: string
  shortMonth: string
  items: ComplianceItem[]
}

// Months in FY 2026-27
export const MONTHS: MonthData[] = [
  {
    month: 'April 2026',
    shortMonth: 'Apr',
    items: [
      {
        name: 'GSTR-1 — Outward Supplies Return (Mar 2026)',
        form: 'GSTR-1',
        dueDate: '11 Apr 2026',
        dueDateDay: 11,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: '₹50/day CGST + ₹50/day SGST (₹20/day each for nil return); max ₹10,000',
      },
      {
        name: 'GSTR-3B — Monthly Summary Return (Mar 2026)',
        form: 'GSTR-3B',
        dueDate: '20 Apr 2026',
        dueDateDay: 20,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: 'Interest @ 18% p.a. on unpaid tax + late fee ₹100/day (₹40/day for nil); max ₹10,000',
      },
      {
        name: 'TDS / TCS Deposit (Mar 2026)',
        form: 'Challan ITNS 281',
        dueDate: '30 Apr 2026',
        dueDateDay: 30,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'TDS/TCS',
        penalty: 'Interest @ 1.5%/month from deduction date to payment date; u/s 271C penalty = 100% of TDS amount',
        note: 'March deductions get an extended deadline — April 30 instead of the usual 7th.',
      },
      {
        name: 'MSME Form I — Outstanding Payments (Oct 2025 – Mar 2026)',
        form: 'MSME-I',
        dueDate: '30 Apr 2026',
        dueDateDay: 30,
        entities: ['Pvt Ltd', 'LLP'],
        category: 'ROC/MCA',
        penalty: '₹25,000 for first default; ₹25,000–₹1,00,000 for each subsequent default (MSMED Act)',
        note: 'Applies only if you owe payments to MSME suppliers outstanding for > 45 days.',
      },
    ],
  },
  {
    month: 'May 2026',
    shortMonth: 'May',
    items: [
      {
        name: 'TDS / TCS Deposit (Apr 2026)',
        form: 'Challan ITNS 281',
        dueDate: '7 May 2026',
        dueDateDay: 7,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'TDS/TCS',
        penalty: 'Interest @ 1.5%/month; penalty u/s 271C = 100% of TDS not deposited',
      },
      {
        name: 'GSTR-1 — Outward Supplies Return (Apr 2026)',
        form: 'GSTR-1',
        dueDate: '11 May 2026',
        dueDateDay: 11,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: '₹100/day (₹40/day for nil return); max ₹10,000',
      },
      {
        name: 'GSTR-3B — Monthly Summary Return (Apr 2026)',
        form: 'GSTR-3B',
        dueDate: '20 May 2026',
        dueDateDay: 20,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: 'Interest @ 18% p.a. on unpaid tax + late fee ₹100/day; max ₹10,000',
      },
      {
        name: 'LLP Annual Return (FY 2025-26)',
        form: 'Form 11',
        dueDate: '30 May 2026',
        dueDateDay: 30,
        entities: ['LLP'],
        category: 'ROC/MCA',
        penalty: '₹100/day for each day of delay; no cap (s. 68 LLP Act)',
      },
      {
        name: 'TDS Return — Q4 FY 2025-26 (Jan–Mar 2026)',
        form: '24Q / 26Q / 27Q / 27EQ',
        dueDate: '31 May 2026',
        dueDateDay: 31,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'TDS/TCS',
        penalty: '₹200/day u/s 234E (capped at TDS amount) + penalty u/s 271H ₹10,000–₹1,00,000',
      },
    ],
  },
  {
    month: 'June 2026',
    shortMonth: 'Jun',
    items: [
      {
        name: 'TDS / TCS Deposit (May 2026)',
        form: 'Challan ITNS 281',
        dueDate: '7 Jun 2026',
        dueDateDay: 7,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'TDS/TCS',
        penalty: 'Interest @ 1.5%/month; penalty u/s 271C = 100% of TDS not deposited',
      },
      {
        name: 'GSTR-1 — Outward Supplies Return (May 2026)',
        form: 'GSTR-1',
        dueDate: '11 Jun 2026',
        dueDateDay: 11,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: '₹100/day (₹40/day for nil return); max ₹10,000',
      },
      {
        name: 'Advance Tax — 1st Installment (min. 15% of annual liability)',
        form: 'Challan ITNS 280',
        dueDate: '15 Jun 2026',
        dueDateDay: 15,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'Income Tax',
        penalty: 'Interest u/s 234C @ 1%/month on the shortfall',
        note: 'Applies if total tax liability for the year exceeds ₹10,000. Proprietors under presumptive u/s 44AD pay only in March.',
      },
      {
        name: 'Form 16 — Salary TDS Certificate (FY 2025-26)',
        form: 'Form 16',
        dueDate: '15 Jun 2026',
        dueDateDay: 15,
        entities: ['Pvt Ltd', 'LLP', 'Partnership'],
        category: 'TDS/TCS',
        penalty: '₹100/day u/s 272A(2)(g)',
        note: 'Must be issued to all salaried employees. Form 16A (non-salary) is due 15 days after the quarterly TDS return due date.',
      },
      {
        name: 'GSTR-3B — Monthly Summary Return (May 2026)',
        form: 'GSTR-3B',
        dueDate: '20 Jun 2026',
        dueDateDay: 20,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: 'Interest @ 18% p.a. on unpaid tax + late fee ₹100/day; max ₹10,000',
      },
    ],
  },
  {
    month: 'July 2026',
    shortMonth: 'Jul',
    items: [
      {
        name: 'TDS / TCS Deposit (Jun 2026)',
        form: 'Challan ITNS 281',
        dueDate: '7 Jul 2026',
        dueDateDay: 7,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'TDS/TCS',
        penalty: 'Interest @ 1.5%/month; penalty u/s 271C = 100% of TDS not deposited',
      },
      {
        name: 'GSTR-1 — Outward Supplies Return (Jun 2026)',
        form: 'GSTR-1',
        dueDate: '11 Jul 2026',
        dueDateDay: 11,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: '₹100/day (₹40/day for nil return); max ₹10,000',
      },
      {
        name: 'GSTR-3B — Monthly Summary Return (Jun 2026)',
        form: 'GSTR-3B',
        dueDate: '20 Jul 2026',
        dueDateDay: 20,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: 'Interest @ 18% p.a. on unpaid tax + late fee ₹100/day; max ₹10,000',
      },
      {
        name: 'ITR Filing — Non-Audit Entities (FY 2025-26 / AY 2026-27)',
        form: 'ITR-1 / ITR-3 / ITR-4 (as applicable)',
        dueDate: '31 Jul 2026',
        dueDateDay: 31,
        entities: ['Proprietorship', 'Partnership', 'LLP'],
        category: 'Income Tax',
        penalty: 'Late fee u/s 234F: ₹1,000 (income ≤ ₹5L) or ₹5,000 + interest u/s 234A @ 1%/month',
        note: 'TODO: Verify if CBDT extends this deadline via circular — it has historically been extended for certain categories.',
      },
      {
        name: 'TDS Return — Q1 FY 2026-27 (Apr–Jun 2026)',
        form: '24Q / 26Q / 27Q / 27EQ',
        dueDate: '31 Jul 2026',
        dueDateDay: 31,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'TDS/TCS',
        penalty: '₹200/day u/s 234E (capped at TDS amount) + penalty u/s 271H ₹10,000–₹1,00,000',
      },
    ],
  },
  {
    month: 'August 2026',
    shortMonth: 'Aug',
    items: [
      {
        name: 'TDS / TCS Deposit (Jul 2026)',
        form: 'Challan ITNS 281',
        dueDate: '7 Aug 2026',
        dueDateDay: 7,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'TDS/TCS',
        penalty: 'Interest @ 1.5%/month; penalty u/s 271C = 100% of TDS not deposited',
      },
      {
        name: 'GSTR-1 — Outward Supplies Return (Jul 2026)',
        form: 'GSTR-1',
        dueDate: '11 Aug 2026',
        dueDateDay: 11,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: '₹100/day (₹40/day for nil return); max ₹10,000',
      },
      {
        name: 'GSTR-3B — Monthly Summary Return (Jul 2026)',
        form: 'GSTR-3B',
        dueDate: '20 Aug 2026',
        dueDateDay: 20,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: 'Interest @ 18% p.a. on unpaid tax + late fee ₹100/day; max ₹10,000',
      },
    ],
  },
  {
    month: 'September 2026',
    shortMonth: 'Sep',
    items: [
      {
        name: 'TDS / TCS Deposit (Aug 2026)',
        form: 'Challan ITNS 281',
        dueDate: '7 Sep 2026',
        dueDateDay: 7,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'TDS/TCS',
        penalty: 'Interest @ 1.5%/month; penalty u/s 271C = 100% of TDS not deposited',
      },
      {
        name: 'GSTR-1 — Outward Supplies Return (Aug 2026)',
        form: 'GSTR-1',
        dueDate: '11 Sep 2026',
        dueDateDay: 11,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: '₹100/day (₹40/day for nil return); max ₹10,000',
      },
      {
        name: 'Advance Tax — 2nd Installment (cumulative 45% of annual liability)',
        form: 'Challan ITNS 280',
        dueDate: '15 Sep 2026',
        dueDateDay: 15,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'Income Tax',
        penalty: 'Interest u/s 234C @ 1%/month on shortfall for 3 months',
      },
      {
        name: 'GSTR-3B — Monthly Summary Return (Aug 2026)',
        form: 'GSTR-3B',
        dueDate: '20 Sep 2026',
        dueDateDay: 20,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: 'Interest @ 18% p.a. on unpaid tax + late fee ₹100/day; max ₹10,000',
      },
      {
        name: 'Annual General Meeting (AGM) — Last Date',
        form: 'Board resolution + statutory notice',
        dueDate: '30 Sep 2026',
        dueDateDay: 30,
        entities: ['Pvt Ltd'],
        category: 'ROC/MCA',
        penalty: 'u/s 99 Companies Act: ₹1,00,000 on company + ₹10,000/officer in default; ROC can extend by 3 months on application',
        note: 'Companies must hold AGM within 6 months of FY end (Mar 31 → Sep 30). OPCs are exempt from AGM.',
      },
      {
        name: 'DIR-3 KYC — Annual KYC for Directors',
        form: 'DIR-3 KYC / DIR-3 KYC-Web',
        dueDate: '30 Sep 2026',
        dueDateDay: 30,
        entities: ['Pvt Ltd', 'LLP'],
        category: 'ROC/MCA',
        penalty: 'DIN gets deactivated immediately; ₹5,000 reactivation fee to restore',
      },
    ],
  },
  {
    month: 'October 2026',
    shortMonth: 'Oct',
    items: [
      {
        name: 'TDS / TCS Deposit (Sep 2026)',
        form: 'Challan ITNS 281',
        dueDate: '7 Oct 2026',
        dueDateDay: 7,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'TDS/TCS',
        penalty: 'Interest @ 1.5%/month; penalty u/s 271C = 100% of TDS not deposited',
      },
      {
        name: 'GSTR-1 — Outward Supplies Return (Sep 2026)',
        form: 'GSTR-1',
        dueDate: '11 Oct 2026',
        dueDateDay: 11,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: '₹100/day (₹40/day for nil return); max ₹10,000',
      },
      {
        name: 'ADT-1 — Auditor Appointment Intimation',
        form: 'ADT-1',
        dueDate: '14 Oct 2026',
        dueDateDay: 14,
        entities: ['Pvt Ltd'],
        category: 'ROC/MCA',
        penalty: '₹300/day, max ₹12,000 + penalty u/s 147 Companies Act',
        note: 'Due within 15 days of AGM. Exact date shifts with your actual AGM date.',
      },
      {
        name: 'GSTR-3B — Monthly Summary Return (Sep 2026)',
        form: 'GSTR-3B',
        dueDate: '20 Oct 2026',
        dueDateDay: 20,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: 'Interest @ 18% p.a. on unpaid tax + late fee ₹100/day; max ₹10,000',
      },
      {
        name: 'AOC-4 — Filing of Financial Statements (FY 2025-26)',
        form: 'AOC-4 / AOC-4 XBRL',
        dueDate: '29 Oct 2026',
        dueDateDay: 29,
        entities: ['Pvt Ltd'],
        category: 'ROC/MCA',
        penalty: '₹100/day additional fee; u/s 137: ₹10,000 minimum up to ₹10,00,000',
        note: 'Due within 30 days of AGM (assumes AGM on Sep 30). OPCs: within 180 days from Mar 31 = Sep 27, 2026. XBRL mandatory for listed/large unlisted companies.',
      },
      {
        name: 'LLP Form 8 — Statement of Account & Solvency (FY 2025-26)',
        form: 'Form 8',
        dueDate: '30 Oct 2026',
        dueDateDay: 30,
        entities: ['LLP'],
        category: 'ROC/MCA',
        penalty: '₹100/day for each day of default; no cap (s. 68 LLP Act)',
      },
      {
        name: 'ITR — Audit-Required Entities (FY 2025-26 / AY 2026-27)',
        form: 'ITR-6 (companies) / ITR-5 (LLP / Partnership)',
        dueDate: '31 Oct 2026',
        dueDateDay: 31,
        entities: ['Pvt Ltd', 'LLP', 'Partnership'],
        category: 'Income Tax',
        penalty: '₹5,000 late fee u/s 234F + interest u/s 234A @ 1%/month',
        note: 'TODO: Verify — CBDT often extends this deadline via circular. Cross-check with the Income Tax portal closer to October.',
      },
      {
        name: 'Tax Audit Report (FY 2025-26)',
        form: 'Form 3CA-3CD / 3CB-3CD',
        dueDate: '31 Oct 2026',
        dueDateDay: 31,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'Income Tax',
        penalty: '½% of turnover or ₹1,50,000, whichever is lower, u/s 271B',
        note: 'Mandatory if turnover > ₹1 crore (business) or gross receipts > ₹50 lakh (profession). Threshold is ₹2 crore if u/s 44AB(a) and 6%/8% profit declared under 44AD. TODO: Verify threshold changes for AY 2026-27.',
      },
      {
        name: 'TDS Return — Q2 FY 2026-27 (Jul–Sep 2026)',
        form: '24Q / 26Q / 27Q / 27EQ',
        dueDate: '31 Oct 2026',
        dueDateDay: 31,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'TDS/TCS',
        penalty: '₹200/day u/s 234E (capped at TDS amount) + penalty u/s 271H ₹10,000–₹1,00,000',
      },
      {
        name: 'MSME Form I — Outstanding Payments (Apr–Sep 2026)',
        form: 'MSME-I',
        dueDate: '31 Oct 2026',
        dueDateDay: 31,
        entities: ['Pvt Ltd', 'LLP'],
        category: 'ROC/MCA',
        penalty: '₹25,000 for first default; ₹25,000–₹1,00,000 per subsequent default',
      },
    ],
  },
  {
    month: 'November 2026',
    shortMonth: 'Nov',
    items: [
      {
        name: 'TDS / TCS Deposit (Oct 2026)',
        form: 'Challan ITNS 281',
        dueDate: '7 Nov 2026',
        dueDateDay: 7,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'TDS/TCS',
        penalty: 'Interest @ 1.5%/month; penalty u/s 271C = 100% of TDS not deposited',
      },
      {
        name: 'GSTR-1 — Outward Supplies Return (Oct 2026)',
        form: 'GSTR-1',
        dueDate: '11 Nov 2026',
        dueDateDay: 11,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: '₹100/day (₹40/day for nil return); max ₹10,000',
      },
      {
        name: 'GSTR-3B — Monthly Summary Return (Oct 2026)',
        form: 'GSTR-3B',
        dueDate: '20 Nov 2026',
        dueDateDay: 20,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: 'Interest @ 18% p.a. on unpaid tax + late fee ₹100/day; max ₹10,000',
      },
      {
        name: 'MGT-7 — Annual Return (FY 2025-26)',
        form: 'MGT-7 / MGT-7A (small companies & OPC)',
        dueDate: '28 Nov 2026',
        dueDateDay: 28,
        entities: ['Pvt Ltd'],
        category: 'ROC/MCA',
        penalty: '₹100/day additional fee; u/s 92(5): ₹50,000–₹5,00,000 penalty',
        note: 'Due within 60 days of AGM (assumes AGM Sep 30). Small companies and OPCs use MGT-7A instead of MGT-7.',
      },
    ],
  },
  {
    month: 'December 2026',
    shortMonth: 'Dec',
    items: [
      {
        name: 'TDS / TCS Deposit (Nov 2026)',
        form: 'Challan ITNS 281',
        dueDate: '7 Dec 2026',
        dueDateDay: 7,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'TDS/TCS',
        penalty: 'Interest @ 1.5%/month; penalty u/s 271C = 100% of TDS not deposited',
      },
      {
        name: 'GSTR-1 — Outward Supplies Return (Nov 2026)',
        form: 'GSTR-1',
        dueDate: '11 Dec 2026',
        dueDateDay: 11,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: '₹100/day (₹40/day for nil return); max ₹10,000',
      },
      {
        name: 'Advance Tax — 3rd Installment (cumulative 75% of annual liability)',
        form: 'Challan ITNS 280',
        dueDate: '15 Dec 2026',
        dueDateDay: 15,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'Income Tax',
        penalty: 'Interest u/s 234C @ 1%/month on shortfall for 3 months',
      },
      {
        name: 'GSTR-3B — Monthly Summary Return (Nov 2026)',
        form: 'GSTR-3B',
        dueDate: '20 Dec 2026',
        dueDateDay: 20,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: 'Interest @ 18% p.a. on unpaid tax + late fee ₹100/day; max ₹10,000',
      },
      {
        name: 'GSTR-9 — Annual GST Return (FY 2025-26)',
        form: 'GSTR-9 / GSTR-9C',
        dueDate: '31 Dec 2026',
        dueDateDay: 31,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: '₹200/day (₹100 CGST + ₹100 SGST), max 0.25% of turnover in the state',
        note: 'GSTR-9 is mandatory for annual turnover > ₹2 crore. GSTR-9C (reconciliation statement) required if turnover > ₹5 crore. Turnover ≤ ₹2 crore: optional but recommended.',
      },
    ],
  },
  {
    month: 'January 2027',
    shortMonth: 'Jan',
    items: [
      {
        name: 'TDS / TCS Deposit (Dec 2026)',
        form: 'Challan ITNS 281',
        dueDate: '7 Jan 2027',
        dueDateDay: 7,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'TDS/TCS',
        penalty: 'Interest @ 1.5%/month; penalty u/s 271C = 100% of TDS not deposited',
      },
      {
        name: 'GSTR-1 — Outward Supplies Return (Dec 2026)',
        form: 'GSTR-1',
        dueDate: '11 Jan 2027',
        dueDateDay: 11,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: '₹100/day (₹40/day for nil return); max ₹10,000',
      },
      {
        name: 'GSTR-3B — Monthly Summary Return (Dec 2026)',
        form: 'GSTR-3B',
        dueDate: '20 Jan 2027',
        dueDateDay: 20,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: 'Interest @ 18% p.a. on unpaid tax + late fee ₹100/day; max ₹10,000',
      },
      {
        name: 'TDS Return — Q3 FY 2026-27 (Oct–Dec 2026)',
        form: '24Q / 26Q / 27Q / 27EQ',
        dueDate: '31 Jan 2027',
        dueDateDay: 31,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'TDS/TCS',
        penalty: '₹200/day u/s 234E (capped at TDS amount) + penalty u/s 271H ₹10,000–₹1,00,000',
      },
    ],
  },
  {
    month: 'February 2027',
    shortMonth: 'Feb',
    items: [
      {
        name: 'TDS / TCS Deposit (Jan 2027)',
        form: 'Challan ITNS 281',
        dueDate: '7 Feb 2027',
        dueDateDay: 7,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'TDS/TCS',
        penalty: 'Interest @ 1.5%/month; penalty u/s 271C = 100% of TDS not deposited',
      },
      {
        name: 'GSTR-1 — Outward Supplies Return (Jan 2027)',
        form: 'GSTR-1',
        dueDate: '11 Feb 2027',
        dueDateDay: 11,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: '₹100/day (₹40/day for nil return); max ₹10,000',
      },
      {
        name: 'GSTR-3B — Monthly Summary Return (Jan 2027)',
        form: 'GSTR-3B',
        dueDate: '20 Feb 2027',
        dueDateDay: 20,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: 'Interest @ 18% p.a. on unpaid tax + late fee ₹100/day; max ₹10,000',
      },
    ],
  },
  {
    month: 'March 2027',
    shortMonth: 'Mar',
    items: [
      {
        name: 'TDS / TCS Deposit (Feb 2027)',
        form: 'Challan ITNS 281',
        dueDate: '7 Mar 2027',
        dueDateDay: 7,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'TDS/TCS',
        penalty: 'Interest @ 1.5%/month; penalty u/s 271C = 100% of TDS not deposited',
      },
      {
        name: 'GSTR-1 — Outward Supplies Return (Feb 2027)',
        form: 'GSTR-1',
        dueDate: '11 Mar 2027',
        dueDateDay: 11,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: '₹100/day (₹40/day for nil return); max ₹10,000',
      },
      {
        name: 'Advance Tax — 4th & Final Installment (100% of annual liability)',
        form: 'Challan ITNS 280',
        dueDate: '15 Mar 2027',
        dueDateDay: 15,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'Income Tax',
        penalty: 'Interest u/s 234B @ 1%/month on total outstanding from Apr 1 onwards',
      },
      {
        name: 'GSTR-3B — Monthly Summary Return (Feb 2027)',
        form: 'GSTR-3B',
        dueDate: '20 Mar 2027',
        dueDateDay: 20,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'GST',
        penalty: 'Interest @ 18% p.a. on unpaid tax + late fee ₹100/day; max ₹10,000',
      },
      {
        name: 'Updated Return — ITR-U for AY 2024-25 (FY 2023-24)',
        form: 'ITR-U',
        dueDate: '31 Mar 2027',
        dueDateDay: 31,
        entities: ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship'],
        category: 'Income Tax',
        penalty: 'Additional tax of 50% of aggregate tax + interest (if filed after 24 months)',
        note: 'TODO: Confirm that AY 2024-25 updated return window is open through Mar 2027. Under s. 139(8A) you can file ITR-U within 2 years of the end of the relevant AY.',
      },
    ],
  },
]

export const CATEGORIES: Category[] = ['GST', 'TDS/TCS', 'Income Tax', 'ROC/MCA', 'ESI/PF']

export const ENTITY_TYPES: EntityType[] = ['Pvt Ltd', 'LLP', 'Partnership', 'Proprietorship']

export const CATEGORY_META: Record<Category, { color: string; description: string }> = {
  GST: {
    color: 'orange',
    description: 'GSTR-1, GSTR-3B, and annual GSTR-9 — for every GST-registered business regardless of entity type.',
  },
  'TDS/TCS': {
    color: 'blue',
    description: 'Monthly TDS deposits, quarterly TDS returns, and Form 16 issuance for employers.',
  },
  'Income Tax': {
    color: 'green',
    description: 'Advance tax installments, ITR filing deadlines, tax audit reports.',
  },
  'ROC/MCA': {
    color: 'purple',
    description: 'Annual filings with MCA — AOC-4, MGT-7, ADT-1 for companies; Form 8 & 11 for LLPs; DIR-3 KYC for directors.',
  },
  'ESI/PF': {
    color: 'yellow',
    description: 'Monthly PF and ESI contributions — due by the 15th of every following month for eligible employers.',
  },
}

// ESI/PF recurring monthly items — shown as a separate always-visible section
export const RECURRING_MONTHLY = [
  {
    name: 'EPF Monthly Contribution',
    form: 'ECR (Electronic Challan cum Return)',
    dueDay: '15th of following month',
    entities: ['Pvt Ltd', 'Partnership'] as EntityType[],
    category: 'ESI/PF' as Category,
    penalty: '₹5,000 + interest u/s 7Q EPF Act; damages u/s 14B up to 25% of arrears',
    note: 'Mandatory for establishments with 20+ employees. Employer contributes 12% of basic salary; employee 12%.',
  },
  {
    name: 'ESI Monthly Contribution',
    form: 'ESI Challan (via ESIC portal)',
    dueDay: '15th of following month',
    entities: ['Pvt Ltd', 'Partnership'] as EntityType[],
    category: 'ESI/PF' as Category,
    penalty: 'Simple interest @ 12% p.a. on arrears u/s 85B ESI Act',
    note: 'Mandatory for establishments with 10+ employees where any employee earns ≤ ₹21,000/month. Employer: 3.25% of wages; Employee: 0.75%.',
  },
]

export const FAQS = [
  {
    q: 'Does this calendar cover all business types equally?',
    a: 'Not equally — intentionally. GST and TDS deadlines apply across the board if your business is registered. ROC filings (AOC-4, MGT-7, ADT-1) are exclusive to Private Limited companies. LLPs have their own annual filings (Form 8, Form 11). Partnerships and proprietorships have the lightest ROC burden but still need to stay current on GST, TDS, and income tax. Use the entity filter to see only what applies to you.',
  },
  {
    q: "I'm on the QRMP scheme — do these dates apply to me?",
    a: "Not fully. QRMP (Quarterly Return Monthly Payment) filers pay GST monthly using IFF/challan but file GSTR-1 and GSTR-3B quarterly. Their quarterly GSTR-1 deadlines are the 13th of the month after the quarter ends, and GSTR-3B is due on the 22nd (Category I states) or 24th (Category II states) of that same month. The monthly dates in this calendar apply only to monthly GST filers (turnover > ₹5 crore, or monthly scheme opted).",
  },
  {
    q: 'What if a due date falls on a public holiday or Sunday?',
    a: "The due date typically rolls over to the next working day — but this is not automatic under every law, and it varies. The GST portal usually allows it; TDS challan payments through banks depend on the bank. The safest move: never wait for the last day. File or pay one business day early.",
  },
  {
    q: 'Does the government ever extend these deadlines?',
    a: "Yes, and more often than you might expect — especially for income tax and GST annual returns. CBDT issues circulars that extend ITR and audit due dates; GSTN pushes notifications for GSTR-9 extensions. We list the statutory deadlines in this calendar. Check the official Income Tax e-filing portal and GSTN for active extensions before each major deadline.",
  },
  {
    q: 'My Pvt Ltd missed the AGM deadline — what can I do?',
    a: "File an application with the ROC for a 3-month extension before the deadline passes (Section 96(2) of Companies Act). If you have already missed it, the company and every officer in default faces a penalty up to ₹1,00,000. A practicing company secretary can help you file a compounding application to regularize the default — it's typically cheaper and faster than contesting it.",
  },
  {
    q: 'Are EPF and ESI mandatory for all businesses?',
    a: "EPF is mandatory for establishments with 20 or more employees. ESI applies to establishments with 10 or more employees where at least one earns ₹21,000/month or less. Once covered, both are mandatory every month — the 15th is your hard cutoff. Some states have lower thresholds, so check the local applicability if you're close to the headcount limit.",
  },
]
