'use client';

import React, { useState, useActionState, useEffect, useRef } from 'react';
import Modal from '../../components/Modal';
import LeadForm from '../../components/LeadForm';
import PopupForm from '../../components/PopupForm';
import { submitLead } from '../../actions';
import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';

const TABS = [
  { id: 'overview', label: 'Overview' },
  { id: 'format', label: 'TAN Format' },
  { id: 'eligibility', label: 'Who Needs TAN' },
  { id: 'comparison', label: 'TAN vs PAN vs TIN' },
  { id: 'process', label: 'Application Process' },
  { id: 'form-49b', label: 'Form 49B' },
  { id: 'documents', label: 'Documents' },
  { id: 'correction', label: 'TAN Correction' },
  { id: 'obligations', label: 'TDS/TCS Obligations' },
  { id: 'penalties', label: 'Penalties' },
  { id: 'benefits', label: 'Benefits' },
  { id: 'faq', label: "FAQ's" },
];

const heroFeatures = [
  'New TAN Application (Form 49B)',
  'TAN Correction & Update',
  'TDS/TCS Return Filing Support',
  'Document Preparation & Verification',
  'Online Filing via NSDL/UTIITSL',
  'Post-Allotment Compliance Guidance',
];

const pricingInclusions = [
  'Free Consultation',
  'Eligibility Assessment',
  'Form 49B Preparation',
  'Document Verification',
  'NSDL/UTIITSL Online Filing',
  'Application Fee Payment',
  'Application Tracking',
  'TAN Allotment Letter',
  'TDS/TCS Compliance Guidance',
  'Post-Registration Support',
];

const overviewFacts: [string, string][] = [
  ['Governing Section', 'Section 203A of the Income-tax Act, 1961'],
  ['Full Form', 'Tax Deduction and Collection Account Number'],
  ['Format', '10-digit alphanumeric — 4 letters, followed by 5 digits, followed by 1 letter'],
  ['Issuing Authority', 'Income Tax Department, through Protean (formerly NSDL) and UTIITSL as authorised intermediaries'],
  ['Application Form', 'Form 49B, filed online through the Protean or UTIITSL portal'],
  ['Government Fee', '₹77 (₹65.50 application charge plus 18% GST)'],
  ['Processing Time', 'Typically 7–15 working days from submission of a complete application; as quick as 3–7 working days for fully paperless, digitally signed applications'],
  ['Validity', 'Lifetime — once allotted, a TAN never expires and requires no periodic renewal'],
];

const formatBreakdown: string[][] = [
  ['First 3 characters', 'An alphabetic jurisdiction code identifying the city or region where the TAN was allotted — for example, MUM for Mumbai or DEL for Delhi'],
  ['4th character', 'The first letter of the deductor\'s name — the individual, company, or entity that applied for the TAN'],
  ['Next 5 characters', 'A unique, system-generated numeric sequence with no independent meaning beyond identifying the specific TAN record'],
  ['Last character', 'An alphabetic check digit generated by the system to detect errors and prevent duplication or forgery'],
];

const eligibilityRows: string[][] = [
  ['Employers', 'Section 192', 'Yes', 'Any employer deducting TDS on salary paid to employees above the applicable exemption threshold'],
  ['Companies & Firms', 'Section 194C / 194J', 'Yes', 'Deducting TDS on contractor payments or professional and technical fees paid in the course of business'],
  ['Banks & Financial Institutions', 'Section 194A', 'Yes', 'Deducting TDS on interest paid on deposits above the prescribed annual threshold'],
  ['E-commerce Operators', 'Section 194-O', 'Yes', 'Deducting TDS on payments made to e-commerce participants selling goods or services through the operator\'s platform'],
  ['Any Person Buying Goods', 'Section 194Q', 'Yes', 'Purchasing goods worth more than ₹50 lakh from a single resident seller in a year, where the buyer\'s turnover exceeded ₹10 crore in the preceding financial year'],
  ['Tenants (Individual/HUF)', 'Section 194-IB', 'No — PAN-based', 'Rent above ₹50,000/month is still subject to TDS, but the tenant deducts and deposits it using their own PAN through Form 26QC, without needing a TAN'],
  ['Property Buyers', 'Section 194-IA', 'No — PAN-based', 'TDS on purchase of immovable property worth ₹50 lakh or more is deducted and deposited using the buyer\'s PAN through Form 26QB, again without a TAN'],
];

const comparisonRows: string[][] = [
  ['Full Form', 'Tax Deduction and Collection Account Number', 'Permanent Account Number', 'Taxpayer Identification Number'],
  ['Purpose', 'Identifies a person responsible for deducting or collecting tax at source', 'Identifies a taxpayer for all income tax purposes and specified financial transactions', 'Historically tracked VAT/CST-registered dealers under state sales tax laws'],
  ['Format', '10-digit alphanumeric (4 letters + 5 digits + 1 letter)', '10-digit alphanumeric (5 letters + 4 digits + 1 letter)', '11-digit numeric, prefixed with a state code'],
  ['Who Needs It', 'Any deductor or collector of tax at source', 'Every taxpayer, entity, or person entering specified financial transactions', 'VAT/CST-registered dealers under the erstwhile state sales tax regime'],
  ['Issuing Authority', 'Income Tax Department, via Protean/UTIITSL', 'Income Tax Department, via Protean/UTIITSL', 'State Commercial Tax Departments'],
  ['Applicable Law', 'Section 203A, Income-tax Act, 1961', 'Section 139A, Income-tax Act, 1961', 'Erstwhile state VAT/CST laws'],
  ['Current Status', 'Active and mandatory for TDS/TCS compliance', 'Active and universally required', 'Largely obsolete — replaced by GSTIN since GST subsumed VAT/CST from July 2017'],
];

const processSteps = [
  { title: 'Visit the NSDL/UTIITSL Portal', desc: 'Go to the official Protean (formerly NSDL) or UTIITSL TAN application portal and select the option for a new TAN application under Form 49B.' },
  { title: 'Fill Form 49B Online', desc: 'Enter the applicant category, name, address, existing PAN (if any), responsible person details, and the nature of TDS/TCS the entity expects to deduct or collect.' },
  { title: 'Upload Supporting Documents', desc: 'Attach identity proof of the responsible person, address proof for the registered office, and entity formation documents such as the Certificate of Incorporation or Partnership Deed, as applicable.' },
  { title: 'Pay the Application Fee (₹77)', desc: 'Complete the payment online via net banking, debit/credit card, or UPI — the fee is fixed at ₹77 regardless of applicant category or entity type.' },
  { title: 'Submit the Application', desc: 'Review all entered details for accuracy, since even minor mismatches with supporting documents are a common reason applications get sent back for correction, and submit the completed Form 49B.' },
  { title: 'Receive TAN (7–15 Working Days)', desc: 'Once processed, the Income Tax Department allots the TAN and dispatches the allotment letter; the number is also available for verification on the e-Filing portal well before the physical letter arrives.' },
];

const form49bFields: string[][] = [
  ['Applicant Category', 'Whether the deductor is a company, individual, HUF, firm, trust, government office, or another specified category — this determines part of the TAN\'s internal formatting'],
  ['Full Name', 'The legal name of the deductor, matching the entity\'s constitution documents or, for individuals, the name as per PAN'],
  ['Address', 'The registered office or principal place of business, which also determines the jurisdictional prefix assigned to the TAN'],
  ['PAN', 'The deductor\'s own Permanent Account Number, where already allotted'],
  ['Responsible Person Details', 'Name and designation of the individual authorised to sign TDS/TCS returns and correspond with the department on the entity\'s behalf'],
  ['Existing TAN', 'Disclosure of any previously allotted TAN, to prevent the system from issuing a duplicate'],
  ['Source of TDS/TCS', 'The nature of the income or transaction on which tax will be deducted or collected — salary, contractor payments, rent, commission, and so on'],
  ['Contact Details', 'Phone number and email address used for all communication regarding the application and its status'],
];

const documentGroups = [
  { group: 'Identity', items: ['PAN card of the applicant entity or individual', 'Aadhaar, Passport, or Voter ID of the responsible person'] },
  { group: 'Address Proof', items: ['Utility bill, rent agreement, or property document for the registered office or principal place of business'] },
  { group: 'Entity Documents', items: ['Certificate of Incorporation, for companies', 'Partnership Deed, for partnership firms', 'LLP Agreement, for Limited Liability Partnerships'] },
  { group: 'Application Form', items: ['Duly signed Form 49B, generated automatically once the online application is completed'] },
];

const tdsObligationRows: string[][] = [
  ['Section 192', 'Salary', 'At the employee\'s applicable slab rate for the year', 'No fixed threshold — applies once taxable income exceeds the basic exemption limit after deductions'],
  ['Section 194A', 'Interest (other than on securities)', '10%', '₹50,000/year for senior citizen bank deposits, ₹40,000/year for other bank/post office deposits, ₹5,000/year otherwise'],
  ['Section 194C', 'Payments to contractors', '1% (individual/HUF payee) / 2% (other payees)', '₹30,000 for a single payment, or ₹1,00,000 in aggregate for the financial year'],
  ['Section 194H', 'Commission or brokerage', '2% (reduced from 5%, effective 1 October 2024)', '₹20,000/year (raised from ₹15,000, effective 1 April 2025)'],
  ['Section 194-I', 'Rent', '2% (plant & machinery) / 10% (land, building, furniture & fittings)', '₹2,40,000/year'],
  ['Section 194J', 'Professional / technical fees', '2% (technical services, call centre operations, royalty for film distribution) / 10% (professional fees, other royalty)', '₹30,000/year per payee'],
  ['Section 194Q', 'Purchase of goods', '0.1% on value exceeding ₹50 lakh', 'Buyer\'s turnover must have exceeded ₹10 crore in the preceding financial year'],
  ['Section 206C', 'Tax collected at source on specified transactions', 'Varies by category — e.g., scrap, minerals, motor vehicles above ₹10 lakh, overseas tour packages, LRS remittances', 'Varies by category; note that TCS on general sale of goods under Section 206C(1H) was omitted effective 1 April 2025, leaving buy-side TDS under Section 194Q as the primary compliance route for high-value goods transactions'],
];

const penaltyRows: string[][] = [
  ['Failure to apply for TAN', 'Section 272BB', 'Penalty of ₹10,000'],
  ['Quoting an incorrect TAN', 'Section 272BB', 'Penalty of ₹10,000'],
  ['Not quoting TAN in TDS/TCS returns, certificates, or challans', 'Section 272BB', 'Penalty of ₹10,000 for each default'],
  ['Late filing of TDS/TCS returns', 'Section 234E', 'Fee of ₹200 per day of delay, capped at the total TDS/TCS amount deductible or collectible for that period'],
];

const benefitCards = [
  { title: 'Legal Compliance', desc: 'Holding a valid TAN before the first TDS deduction keeps the deductor on the right side of Section 203A and avoids the ₹10,000 penalty under Section 272BB for operating without one.' },
  { title: 'Smooth TDS Filing', desc: 'Every quarterly TDS/TCS return requires a valid TAN to even be accepted on the e-Filing portal — without it, returns simply cannot be filed, however accurate the underlying figures are.' },
  { title: 'Banking Operations', desc: 'Banks and institutional counterparties routinely ask for a valid TAN as part of onboarding or compliance verification for business accounts and vendor payment processing.' },
  { title: 'Valid Certificates (Form 16/16A/16B/16C)', desc: 'TAN is a mandatory field on every TDS certificate issued to employees and vendors — without a correctly quoted TAN, the recipient cannot claim their TDS credit while filing their own return.' },
  { title: 'Employee & Vendor Trust', desc: 'Timely TDS deposit and correctly issued certificates, both dependent on a properly registered TAN, signal financial discipline to employees, contractors, and vendors relying on those credits.' },
  { title: 'Government Contract Eligibility', desc: 'Tenders and empanelment processes for government and PSU contracts commonly require proof of TAN registration and TDS compliance history as part of the financial eligibility criteria.' },
];

const faqs = [
  { q: 'What is TAN?', a: 'TAN, or Tax Deduction and Collection Account Number, is a 10-digit alphanumeric identifier issued under Section 203A of the Income-tax Act, 1961 to any person or entity responsible for deducting or collecting tax at source.' },
  { q: 'Who needs to apply for TAN?', a: 'Employers deducting TDS on salary, businesses deducting TDS on contractor or professional payments, banks deducting TDS on interest, e-commerce operators under Section 194-O, and buyers of goods above ₹50 lakh under Section 194Q all need a TAN before they can deduct and deposit tax at source.' },
  { q: 'What does the TAN format mean?', a: 'A TAN reads as 4 letters, 5 digits, and 1 letter — the first 3 letters denote the jurisdiction city, the 4th letter is the first letter of the deductor\'s name, the 5 digits are a unique system-generated sequence, and the final letter is a check digit that guards against errors and duplication.' },
  { q: 'What is Form 49B?', a: 'Form 49B is the prescribed application form for allotment of a new TAN, filed online through the Protean (formerly NSDL) or UTIITSL portal, capturing the applicant\'s category, identity, address, and the nature of TDS/TCS they will be responsible for.' },
  { q: 'What is the cost of TAN registration?', a: 'The government application fee is a fixed ₹77 (₹65.50 plus 18% GST), payable online at the time of submitting Form 49B, regardless of the applicant\'s category or entity type.' },
  { q: 'How long does TAN allotment take?', a: 'Processing typically takes 7–15 working days from submission of a complete, error-free application, though fully paperless applications verified digitally can be processed in as little as 3–7 working days.' },
  { q: 'What is the online application process for TAN?', a: 'The process runs through six broad steps: visiting the NSDL/UTIITSL portal, filling Form 49B online, uploading supporting documents, paying the ₹77 application fee, submitting the application, and receiving the TAN allotment within 7–15 working days.' },
  { q: 'What is the difference between TAN, PAN and TIN?', a: 'TAN identifies a person responsible for deducting or collecting tax at source, PAN identifies a taxpayer for all income tax purposes, and TIN was historically used to track VAT/CST-registered dealers under state sales tax laws — TIN is now largely obsolete, having been superseded by the GSTIN since GST replaced VAT/CST in July 2017.' },
  { q: 'Is TAN mandatory for salary payments?', a: 'Yes — any employer required to deduct TDS on employee salaries under Section 192 must first obtain a TAN, since the quarterly salary TDS return (Form 24Q) cannot be filed without one.' },
  { q: 'Can an individual apply for TAN?', a: 'Yes, an individual can apply for TAN if they are responsible for deducting TDS in a business or professional capacity — for example, a sole proprietor paying contractors or professional fees above the prescribed thresholds. Individuals making one-off large payments like rent (Section 194-IB) or property purchase (Section 194-IA) do not need a TAN, since those provisions use PAN-based compliance instead.' },
  { q: 'What are the penalties for TAN non-compliance?', a: 'Failure to apply for TAN, quoting an incorrect TAN, or not quoting TAN in returns, certificates, or challans each attracts a penalty of ₹10,000 under Section 272BB, while late filing of TDS/TCS returns separately attracts a fee of ₹200 per day under Section 234E, capped at the TDS/TCS amount involved.' },
  { q: 'How do I correct details on an existing TAN?', a: 'Corrections — to name, address, category, contact details, responsible person, or PAN linking — are filed through a TAN Change Request Form on the same NSDL/UTIITSL portal, for a fee of ₹77, and are typically processed within 7–10 working days.' },
  { q: 'Can a company or entity have multiple TANs?', a: 'Ideally no — a single entity is meant to hold one TAN per deducting office/branch structure it operates. Where duplicate TANs have been inadvertently obtained, the entity should apply to have the extra TAN cancelled and continue operating under one, since quoting inconsistent TANs across returns can invite compliance queries.' },
  { q: 'What is the difference between TDS and TCS?', a: 'TDS (Tax Deducted at Source) is withheld by the person making a payment — such as salary, rent, or professional fees — before crediting it to the recipient, while TCS (Tax Collected at Source) is added on and collected by the seller from the buyer at the time of sale of specified goods or services, and both ultimately require the responsible party to hold a TAN.' },
  { q: 'What are the important TDS sections to know?', a: 'Commonly encountered provisions include Section 192 for salary, 194A for interest, 194C for contractor payments, 194H for commission, 194-I for rent, 194J for professional and technical fees, and 194Q for purchase of goods — each carrying its own rate and threshold.' },
  { q: 'What are the TDS/TCS deposit deadlines?', a: 'Tax deducted or collected in any month must generally be deposited with the government by the 7th of the following month, with one exception — TDS/TCS for the month of March must be deposited by 30 April of the same year.' },
  { q: 'Is TAN required for rent payments?', a: 'It depends on who is paying. A business or entity deducting TDS on rent under Section 194-I needs a TAN, but an individual or HUF (not subject to tax audit) paying monthly rent above ₹50,000 deducts TDS under Section 194-IB using their own PAN through Form 26QC, without needing a TAN at all.' },
  { q: 'What documents are required for TAN registration?', a: 'A typical application needs identity proof of the responsible person (PAN, Aadhaar, Passport, or Voter ID), address proof for the registered office or principal place of business, and entity formation documents such as the Certificate of Incorporation, Partnership Deed, or LLP Agreement, as applicable.' },
  { q: 'How can I check my TAN application status online?', a: 'The Protean (formerly NSDL) portal allows applicants to track status using the acknowledgment number generated at the time of submission, showing whether the application is under process, has been sent for correction, or has resulted in TAN allotment.' },
  { q: 'What happens if I quote the wrong TAN?', a: 'Quoting an incorrect TAN in a TDS/TCS return, certificate, or challan attracts a penalty of ₹10,000 under Section 272BB, and can also disrupt the recipient\'s ability to correctly claim TDS credit against the wrongly quoted number.' },
  { q: 'Does TAN expire or need renewal?', a: 'No. A TAN, once allotted, is valid for the lifetime of the entity or individual and never needs to be renewed — it remains active as long as the holder continues to exist or operate.' },
  { q: 'Is TAN required for property purchase TDS under Section 194-IA?', a: 'No. TDS on the purchase of immovable property worth ₹50 lakh or more is deducted and deposited using the buyer\'s own PAN through Form 26QB, a combined challan-cum-statement — this is a deliberate simplification so individual property buyers don\'t need to register for a TAN for a one-off transaction.' },
  { q: 'Can TAN and PAN be the same number?', a: 'No, TAN and PAN are entirely separate identifiers with different formats and different purposes — PAN identifies the taxpayer, while TAN identifies the entity in its capacity as a deductor or collector of tax at source. Many businesses hold both simultaneously, using PAN for their own tax filings and TAN for TDS/TCS compliance.' },
  { q: 'How does ComplianceBharo assist with TAN registration?', a: 'We assess whether your situation actually requires TAN registration, prepare and file Form 49B with the correct category and details, verify supporting documents before submission, track the application through to allotment, and stay available for TAN corrections or TDS/TCS compliance queries afterward.' },
];

function CheckIcon({ className = 'h-4 w-4' }: { className?: string }) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className={className}>
      <path fillRule="evenodd" d="M16.704 4.153a.75.75 0 0 1 .143 1.052l-8 10.5a.75.75 0 0 1-1.127.075l-4.5-4.5a.75.75 0 0 1 1.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 0 1 1.05-.143Z" clipRule="evenodd" />
    </svg>
  );
}

function DataTable({ headers, rows, dm }: { headers: string[]; rows: string[][]; dm: boolean }) {
  return (
    <div className={`overflow-x-auto rounded-2xl border ${dm ? 'border-slate-800' : 'border-slate-200'}`}>
      <table className="w-full text-left text-sm">
        <thead>
          <tr className={dm ? 'bg-slate-900/60' : 'bg-slate-100'}>
            {headers.map((h) => (
              <th key={h} className={`whitespace-nowrap px-4 py-3 font-semibold ${dm ? 'text-white' : 'text-slate-900'}`}>
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody className={`divide-y ${dm ? 'divide-slate-800' : 'divide-slate-200'}`}>
          {rows.map((row, i) => (
            <tr key={i} className={dm ? 'hover:bg-slate-900/40' : 'hover:bg-slate-50'}>
              {row.map((cell, j) => (
                <td key={j} className={`px-4 py-3 align-top leading-relaxed ${dm ? 'text-slate-300' : 'text-slate-700'}`}>
                  {cell}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default function TANClient() {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isDarkMode, setIsDarkMode] = useState(true);
  const [activeFaq, setActiveFaq] = useState<number | null>(null);
  const [activeTab, setActiveTab] = useState('overview');
  const [state, formAction, pending] = useActionState(submitLead, { success: undefined, message: '', errors: {} });
  const formRef = useRef<HTMLFormElement>(null);

  const dm = isDarkMode;

  useEffect(() => {
    if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
      setIsDarkMode(true);
    }
  }, []);

  useEffect(() => {
    if (state?.success) {
      formRef.current?.reset();
    }
  }, [state]);

  const scrollToSection = (e: React.MouseEvent<HTMLAnchorElement>, id: string) => {
    e.preventDefault();
    const el = document.getElementById(id);
    if (el) {
      const offset = 110;
      const y = el.getBoundingClientRect().top + window.scrollY - offset;
      window.scrollTo({ top: y, behavior: 'smooth' });
      setActiveTab(id);
    }
  };

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActiveTab(entry.target.id);
          }
        });
      },
      { rootMargin: '-140px 0px -60% 0px' }
    );

    TABS.forEach((tab) => {
      const el = document.getElementById(tab.id);
      if (el) observer.observe(el);
    });

    return () => observer.disconnect();
  }, []);

  return (
    <div className={`min-h-screen transition-colors duration-300 ${dm ? 'bg-[#0f172a] text-slate-200' : 'bg-slate-50 text-slate-800'}`}>
      <Navbar isDarkMode={dm} setIsDarkMode={setIsDarkMode} breadcrumb="TAN Registration" />

      {/* Hero */}
      <section className={`relative pt-6 pb-16 lg:pt-10 lg:pb-24 overflow-hidden transition-colors duration-300 ${dm ? 'bg-slate-950' : 'bg-white'}`}>
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div className="absolute -top-1/2 -right-1/4 w-full h-full bg-gradient-to-b from-brand-orange/10 to-transparent blur-3xl rounded-full" />
        </div>
        <div className="relative mx-auto max-w-7xl px-6">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
            <div className="lg:col-span-7 space-y-8">
              <div className="flex flex-col gap-3">
                <div className={`inline-flex self-start items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-semibold shadow-sm ${dm ? 'border-orange-500/25 bg-orange-500/5 text-brand-orange' : 'border-orange-500/35 bg-orange-500/10 text-orange-600'}`}>
                  <span className="flex h-1.5 w-1.5 rounded-full bg-brand-orange"></span>
                  TDS/TCS Registration &amp; Compliance
                  <span className="font-bold ml-0.5">&gt;</span>
                </div>

                <h1 className={`text-3xl font-extrabold tracking-tight sm:text-4xl lg:text-5xl lg:leading-[1.1] ${dm ? 'text-white' : 'text-slate-900'}`}>
                  <span className="bg-gradient-to-r from-orange-400 to-amber-500 bg-clip-text text-transparent">TAN Registration</span><br />
                  in India
                </h1>

                <p className={`max-w-xl text-lg leading-relaxed ${dm ? 'text-slate-300' : 'text-slate-600'}`}>
                  Get Your TAN Number for TDS/TCS Compliance
                </p>

                <p className={`max-w-xl text-sm font-semibold ${dm ? 'text-slate-400' : 'text-slate-500'}`}>
                  Form 49B Preparation. NSDL/UTIITSL e-Filing. Allotment in 7-15 Working Days. Starting at <span className="text-brand-orange">₹999</span> ComplianceBharo professional fee for end-to-end assistance. Government/statutory fees are charged separately at actuals.
                </p>

                {/* Features Grid */}
                <div className={`mt-2 rounded-2xl border p-5 sm:p-6 shadow-sm ${dm ? 'border-slate-800 bg-slate-900/50' : 'border-slate-200 bg-white'}`}>
                  <div className="grid grid-cols-1 gap-y-4 gap-x-6 sm:grid-cols-2">
                    {heroFeatures.map((feature, idx) => (
                      <div key={idx} className="flex items-start gap-2.5">
                        <CheckIcon className={`h-4 w-4 shrink-0 mt-0.5 ${dm ? 'text-orange-400' : 'text-orange-500'}`} />
                        <span className={`text-sm font-medium leading-snug ${dm ? 'text-slate-200' : 'text-slate-700'}`}>{feature}</span>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Bottom Info Bar */}
                <div className="flex flex-col sm:flex-row gap-4 sm:items-center sm:justify-between text-xs">
                  <div className={`flex items-center gap-1.5 font-medium ${dm ? 'text-slate-400' : 'text-slate-500'}`}>
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-4 h-4 text-brand-orange">
                      <path fillRule="evenodd" d="M12.516 2.17a.75.75 0 00-1.032 0 11.209 11.209 0 01-7.877 3.08.75.75 0 00-.722.515A12.74 12.74 0 002.25 9.75c0 5.942 4.064 10.933 9.568 12.318a.75.75 0 00.364 0c5.504-1.385 9.568-6.376 9.568-12.318 0-1.36-.219-2.665-.635-3.985a.75.75 0 00-.722-.515 11.209 11.209 0 01-7.877-3.08zM10.25 13.75l-2.03-2.03a.75.75 0 00-1.06 1.06l2.56 2.56a.75.75 0 001.06 0l5.5-5.5a.75.75 0 00-1.06-1.06l-4.97 4.97z" clipRule="evenodd" />
                    </svg>
                    Reviewed by Industry Experts &amp; TDS Compliance Specialists.
                  </div>
                </div>
              </div>
            </div>

            <div id="lead-form" className="lg:col-span-5 relative lg:ml-8 mt-12 lg:mt-0">
              <LeadForm serviceName={"TAN Registration"} dm={isDarkMode} />
            </div>
          </div>
        </div>
      </section>

      {/* Pricing Plans */}
      <section className={`pt-6 pb-16 lg:pt-10 ${dm ? 'bg-slate-900/30' : 'bg-slate-50'}`}>
        <div className="mx-auto max-w-4xl px-6">
          <div className="text-center mb-12">
            <div className={`inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-semibold mb-4 ${dm ? 'border-orange-500/25 bg-orange-500/5 text-brand-orange' : 'border-orange-500/35 bg-orange-500/10 text-orange-600'}`}>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="2" stroke="currentColor" className="w-4 h-4">
                <path strokeLinecap="round" strokeLinejoin="round" d="M9.568 3H5.25A2.25 2.25 0 003 5.25v4.318c0 .597.237 1.17.659 1.591l9.581 9.581c.699.699 1.78.872 2.607.33a18.095 18.095 0 005.223-5.223c.542-.827.369-1.908-.33-2.607L11.16 3.66A2.25 2.25 0 009.568 3z" />
                <path strokeLinecap="round" strokeLinejoin="round" d="M6 6h.008v.008H6V6z" />
              </svg>
              PRICING
            </div>
            <h2 className={`text-3xl font-extrabold tracking-tight sm:text-4xl ${dm ? 'text-white' : 'text-slate-900'}`}>
              Simple &amp; Transparent Pricing
            </h2>
          </div>

          <div className="relative mt-8 rounded-3xl shadow-2xl">
            <div className="bg-brand-orange px-8 pt-12 pb-24 text-center relative rounded-t-3xl">
              <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-1/2">
                <div className="bg-amber-400 text-black px-5 py-1.5 rounded-full text-xs font-bold shadow-md flex items-center gap-1.5">
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-4 h-4">
                    <path fillRule="evenodd" d="M12.963 2.286a.75.75 0 00-1.071-.136 9.742 9.742 0 00-3.539 6.177A7.547 7.547 0 016.648 6.61a.75.75 0 00-1.152.082A9 9 0 1015.68 4.534a7.46 7.46 0 01-2.717-2.248zM15.75 14.25a3.75 3.75 0 11-7.313-1.172c.628.465 1.35.81 2.133 1a5.99 5.99 0 011.925-3.545 3.75 3.75 0 013.255 3.717z" clipRule="evenodd" />
                  </svg>
                  MOST POPULAR
                </div>
              </div>
              <h3 className="text-2xl sm:text-3xl font-bold text-white mb-6">
                TAN Registration Package
              </h3>
              <div className="text-white flex flex-col sm:flex-row items-center justify-center gap-3 mb-6">
                <span className="text-lg opacity-90">From</span>
                <span className="text-6xl font-extrabold tracking-tight">
                  ₹999
                </span>
                <span className="text-sm opacity-90 max-w-[150px] text-left leading-tight">ComplianceBharo professional fee for assistance</span>
              </div>
              <div className="text-white/90 text-sm flex items-center justify-center gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="2" stroke="currentColor" className="w-4 h-4"><path strokeLinecap="round" strokeLinejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                Allotment typically within 7-15 working days
              </div>
            </div>

            <div className={`relative -mt-16 mx-4 sm:mx-8 mb-8 rounded-2xl p-6 sm:p-8 shadow-xl ${dm ? 'bg-slate-900 border border-slate-800' : 'bg-white border border-slate-100'}`}>
              <div className="flex flex-wrap justify-center gap-4 mb-8">
                <span className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-semibold border ${dm ? 'bg-green-500/10 text-green-400 border-green-500/20' : 'bg-green-50 text-green-700 border-green-200'}`}>
                  <CheckIcon className="w-3.5 h-3.5" /> Application support
                </span>
                <span className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-semibold border ${dm ? 'bg-orange-500/10 text-brand-orange border-orange-500/20' : 'bg-orange-50 text-orange-700 border-orange-200'}`}>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="2.5" stroke="currentColor" className="w-3.5 h-3.5"><path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12c0 1.268-.63 2.39-1.593 3.068a3.745 3.745 0 01-1.043 3.296 3.745 3.745 0 01-3.296 1.043A3.745 3.745 0 0112 21c-1.268 0-2.39-.63-3.068-1.593a3.746 3.746 0 01-3.296-1.043 3.745 3.745 0 01-1.043-3.296A3.745 3.745 0 013 12c0-1.268.63-2.39 1.593-3.068a3.745 3.745 0 011.043-3.296 3.746 3.746 0 013.296-1.043A3.746 3.746 0 0112 3c1.268 0 2.39.63 3.068 1.593a3.746 3.746 0 013.296 1.043 3.746 3.746 0 011.043 3.296A3.745 3.745 0 0121 12z" /></svg> Professional assistance
                </span>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-y-4 gap-x-8 mb-8">
                {pricingInclusions.map((feature, idx) => (
                  <div key={idx} className="flex items-start gap-2.5">
                    <CheckIcon className={`h-5 w-5 shrink-0 ${dm ? 'text-green-400' : 'text-green-500'}`} />
                    <span className={`text-[15px] font-medium leading-snug ${dm ? 'text-slate-200' : 'text-slate-700'}`}>{feature}</span>
                  </div>
                ))}
              </div>

              <div className="flex justify-center mt-10">
                <a href="#lead-form" onClick={(e) => scrollToSection(e, 'lead-form')} className={`inline-flex items-center gap-2 text-white font-bold py-3.5 px-8 rounded-xl shadow-lg transition-all active:scale-95 text-base ${dm ? 'bg-slate-800 hover:bg-slate-700 shadow-slate-900/50' : 'bg-slate-900 hover:bg-slate-800 shadow-slate-900/20'}`}>
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-5 h-5">
                    <path fillRule="evenodd" d="M9 4.5a.75.75 0 01.721.544l.813 2.846a3.75 3.75 0 002.576 2.576l2.846.813a.75.75 0 010 1.442l-2.846.813a3.75 3.75 0 00-2.576 2.576l-.813 2.846a.75.75 0 01-1.442 0l-.813-2.846a3.75 3.75 0 00-2.576-2.576l-2.846-.813a.75.75 0 010-1.442l2.846-.813A3.75 3.75 0 007.466 7.89l.813-2.846A.75.75 0 019 4.5zM18 1.5a.75.75 0 01.728.568l.258 1.036c.236.94.97 1.674 1.91 1.91l1.036.258a.75.75 0 010 1.456l-1.036.258c-.94.236-1.674.97-1.91 1.91l-.258 1.036a.75.75 0 01-1.456 0l-.258-1.036a2.625 2.625 0 00-1.91-1.91l-1.036-.258a.75.75 0 010-1.456l1.036-.258a2.625 2.625 0 001.91-1.91l.258-1.036A.75.75 0 0118 1.5zM16.5 15a.75.75 0 01.712.513l.394 1.183c.15.447.5.799.948.948l1.183.395a.75.75 0 010 1.422l-1.183.395c-.447.15-.799.5-.948.948l-.395 1.183a.75.75 0 01-1.422 0l-.395-1.183a1.5 1.5 0 00-.948-.948l-1.183-.395a.75.75 0 010-1.422l1.183-.395c.447-.15.799-.5.948-.948l.395-1.183A.75.75 0 0116.5 15z" clipRule="evenodd" />
                  </svg>
                  Get Expert Assistance
                </a>
              </div>

              <div className="mt-8 text-center text-xs text-slate-500 font-medium px-4">
                Listed amount is ComplianceBharo&apos;s professional charge for end-to-end assistance. Government/statutory fees are charged separately at actuals.
              </div>
            </div>

            {/* Trust markers */}
            <div className={`mt-8 py-6 border-t ${dm ? 'border-slate-800 text-slate-300' : 'border-slate-100 text-slate-700'} grid grid-cols-1 sm:grid-cols-3 gap-6 text-center text-sm font-semibold mx-8`}>
              <div className="flex items-center justify-center gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="2" stroke="currentColor" className="w-5 h-5 text-brand-orange"><path strokeLinecap="round" strokeLinejoin="round" d="M12 6v12m-3-2.818l.879.659c1.171.879 3.07.879 4.242 0 1.172-.879 1.172-2.303 0-3.182C13.536 12.219 12.768 12 12 12c-.725 0-1.45-.22-2.003-.659-1.106-.879-1.106-2.303 0-3.182s2.9-.879 4.006 0l.415.33M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                Transparent scope
              </div>
              <div className="flex items-center justify-center gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="2" stroke="currentColor" className="w-5 h-5 text-brand-orange"><path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12c0 1.268-.63 2.39-1.593 3.068a3.745 3.745 0 01-1.043 3.296 3.745 3.745 0 01-3.296 1.043A3.745 3.745 0 0112 21c-1.268 0-2.39-.63-3.068-1.593a3.746 3.746 0 01-3.296-1.043 3.745 3.745 0 01-1.043-3.296A3.745 3.745 0 013 12c0-1.268.63-2.39 1.593-3.068a3.745 3.745 0 011.043-3.296 3.746 3.746 0 013.296-1.043A3.746 3.746 0 0112 3c1.268 0 2.39.63 3.068 1.593a3.746 3.746 0 013.296 1.043 3.746 3.746 0 011.043 3.296A3.745 3.745 0 0121 12z" /></svg>
                Secure payment
              </div>
              <div className="flex items-center justify-center gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="2" stroke="currentColor" className="w-5 h-5 text-brand-orange"><path strokeLinecap="round" strokeLinejoin="round" d="M14 10h4.764a2 2 0 011.789 2.894l-3.5 7A2 2 0 0115.263 21h-4.017c-.163 0-.326-.02-.485-.06L7 20m7-10V5a2 2 0 00-2-2h-.095c-.5 0-.905.405-.905.905 0 .714-.211 1.412-.608 2.006L7 11v9m7-10h-2M7 20H5a2 2 0 01-2-2v-6a2 2 0 012-2h2.5" /></svg>
                Application support
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Sticky Sub-Navigation */}
      <div className={`sticky top-0 z-40 border-b backdrop-blur-xl ${dm ? 'border-slate-800 bg-slate-950/80' : 'border-slate-200 bg-white/80'}`}>
        <div className="mx-auto max-w-7xl px-6">
          <div className="flex space-x-8 overflow-x-auto hide-scrollbar">
            {TABS.map((tab) => (
              <a
                key={tab.id}
                href={`#${tab.id}`}
                onClick={(e) => scrollToSection(e, tab.id)}
                className={`whitespace-nowrap py-4 text-sm font-semibold border-b-2 transition-colors ${
                  activeTab === tab.id
                    ? 'border-brand-orange text-brand-orange'
                    : `border-transparent ${dm ? 'text-slate-400 hover:text-slate-200' : 'text-slate-500 hover:text-slate-800'}`
                }`}
              >
                {tab.label}
              </a>
            ))}
          </div>
        </div>
      </div>

      <div className="mx-auto max-w-7xl px-6 py-12 lg:py-16 grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-8 space-y-16">

          {/* 1. Overview */}
          <div id="overview" className="scroll-mt-24">
            <h2 className={`text-2xl font-extrabold mb-6 ${dm ? 'text-white' : 'text-slate-900'}`}>What Is TAN Registration?</h2>
            <div className={`space-y-4 text-base leading-relaxed mb-6 ${dm ? 'text-slate-300' : 'text-slate-600'}`}>
              <p>
                TAN — short for <strong className={dm ? 'text-white' : 'text-slate-900'}>Tax Deduction and Collection Account Number</strong> — is a 10-digit alphanumeric identifier that <strong className={dm ? 'text-white' : 'text-slate-900'}>Section 203A of the Income-tax Act, 1961</strong> makes mandatory for anyone deducting or collecting tax at source. It exists purely to track a deductor's TDS/TCS obligations and has nothing to do with the deductor's own income tax assessment, which is what PAN is for.
              </p>
              <p>
                TAN is allotted online through <strong className={dm ? 'text-white' : 'text-slate-900'}>Protean (formerly NSDL) or UTIITSL</strong>, the two authorised intermediaries appointed by the Income Tax Department, using <strong className={dm ? 'text-white' : 'text-slate-900'}>Form 49B</strong>. The application carries a fixed government fee of <strong className={dm ? 'text-white' : 'text-slate-900'}>₹77</strong> and typically results in allotment within <strong className={dm ? 'text-white' : 'text-slate-900'}>7–15 working days</strong>, though fully digital, paperless applications can move faster.
              </p>
              <p>
                Once allotted, TAN has to be quoted on every TDS/TCS challan, certificate, and return the deductor files — without it, the quarterly TDS return simply cannot be submitted, and any TDS certificate issued to an employee or vendor becomes practically useless for their own tax credit.
              </p>
            </div>
            <DataTable headers={['Parameter', 'Details']} rows={overviewFacts} dm={dm} />
          </div>

          {/* 2. TAN Format */}
          <div id="format" className="scroll-mt-24">
            <h2 className={`text-2xl font-extrabold mb-2 ${dm ? 'text-white' : 'text-slate-900'}`}>Understanding the TAN Format</h2>
            <p className={`text-sm leading-relaxed mb-6 ${dm ? 'text-slate-400' : 'text-slate-600'}`}>
              A TAN — for example, something like MUMD12345E — is built from four distinct segments, each carrying its own meaning.
            </p>
            <DataTable headers={['Segment', 'What It Represents']} rows={formatBreakdown} dm={dm} />
            <div className={`mt-6 rounded-2xl border p-4 text-sm leading-relaxed ${dm ? 'border-slate-800 bg-slate-900/40 text-slate-300' : 'border-slate-200 bg-white text-slate-700'}`}>
              Unlike several other business registrations, a TAN carries <strong className={dm ? 'text-white' : 'text-slate-900'}>lifetime validity</strong> — there is no periodic renewal, no expiry date, and no need to reapply so long as the deductor entity continues to exist.
            </div>
          </div>

          {/* 3. Who Needs TAN */}
          <div id="eligibility" className="scroll-mt-24">
            <h2 className={`text-2xl font-extrabold mb-2 ${dm ? 'text-white' : 'text-slate-900'}`}>Who Needs TAN?</h2>
            <p className={`text-sm leading-relaxed mb-6 ${dm ? 'text-slate-400' : 'text-slate-600'}`}>
              Most TDS/TCS obligations do require a TAN — but a few specific, individual-facing provisions were deliberately designed to work through PAN instead, and it's worth knowing which is which.
            </p>
            <DataTable headers={['Category', 'Applicable Section', 'TAN Required?', 'When It Applies']} rows={eligibilityRows} dm={dm} />
            <div className={`mt-6 rounded-2xl border p-4 text-sm leading-relaxed ${dm ? 'border-amber-500/30 bg-amber-500/10 text-amber-200' : 'border-amber-400/50 bg-amber-50 text-amber-800'}`}>
              <strong>PAN-Based Exceptions: </strong>
              Sections 194-IA (property purchase) and 194-IB (rent by individuals/HUFs) were built as one-off, TAN-free compliance routes — tax is deducted and deposited using the payer's PAN through a combined challan-cum-statement (Form 26QB or 26QC respectively), so a resident individual making a single large payment never needs to register for a TAN just for that transaction.
            </div>
          </div>

          {/* 4. TAN vs PAN vs TIN */}
          <div id="comparison" className="scroll-mt-24">
            <h2 className={`text-2xl font-extrabold mb-2 ${dm ? 'text-white' : 'text-slate-900'}`}>TAN vs PAN vs TIN</h2>
            <p className={`text-sm leading-relaxed mb-6 ${dm ? 'text-slate-400' : 'text-slate-600'}`}>
              These three identifiers are often confused with one another, but each serves a distinct purpose under a different piece of legislation.
            </p>
            <DataTable headers={['Parameter', 'TAN', 'PAN', 'TIN']} rows={comparisonRows} dm={dm} />
          </div>

          {/* 5. Application Process */}
          <div id="process" className="scroll-mt-24">
            <h2 className={`text-2xl font-extrabold mb-6 ${dm ? 'text-white' : 'text-slate-900'}`}>TAN Application Process — Step by Step</h2>
            <div className="relative border-l-2 border-brand-orange/30 ml-3 md:ml-4 space-y-8">
              {processSteps.map((step, i) => (
                <div key={i} className="relative pl-8">
                  <span className={`absolute -left-[17px] top-1 flex h-8 w-8 items-center justify-center rounded-full text-sm font-extrabold ring-4 ${dm ? 'bg-slate-950 ring-slate-950 text-brand-orange border border-brand-orange' : 'bg-white ring-white text-brand-orange border border-brand-orange'}`}>
                    {i + 1}
                  </span>
                  <h3 className={`text-lg font-bold mb-2 ${dm ? 'text-white' : 'text-slate-900'}`}>{step.title}</h3>
                  <p className={`text-sm leading-relaxed ${dm ? 'text-slate-400' : 'text-slate-600'}`}>{step.desc}</p>
                </div>
              ))}
            </div>
          </div>

          {/* 6. Form 49B Explained */}
          <div id="form-49b" className="scroll-mt-24">
            <h2 className={`text-2xl font-extrabold mb-2 ${dm ? 'text-white' : 'text-slate-900'}`}>Form 49B Explained</h2>
            <p className={`text-sm leading-relaxed mb-6 ${dm ? 'text-slate-400' : 'text-slate-600'}`}>
              Every field in Form 49B feeds directly into how the TAN is structured and how the Income Tax Department will correspond with the deductor going forward.
            </p>
            <DataTable headers={['Field', 'What It Captures']} rows={form49bFields} dm={dm} />
          </div>

          {/* 7. Documents Required */}
          <div id="documents" className="scroll-mt-24">
            <h2 className={`text-2xl font-extrabold mb-2 ${dm ? 'text-white' : 'text-slate-900'}`}>Documents Required for TAN Registration</h2>
            <p className={`text-sm leading-relaxed mb-6 ${dm ? 'text-slate-400' : 'text-slate-600'}`}>
              Documentation for TAN is comparatively light — most of it overlaps with what an entity already holds for its PAN or incorporation filings.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {documentGroups.map((group) => (
                <div key={group.group} className={`p-5 rounded-2xl border ${dm ? 'border-slate-800 bg-slate-900/40' : 'border-slate-200 bg-white'}`}>
                  <h3 className={`text-sm font-bold uppercase tracking-wide mb-4 ${dm ? 'text-brand-orange' : 'text-orange-600'}`}>{group.group}</h3>
                  <ul className="space-y-3">
                    {group.items.map((item, i) => (
                      <li key={i} className="flex items-start gap-2.5">
                        <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-orange-500/10 text-brand-orange mt-0.5">
                          <CheckIcon className="h-3 w-3" />
                        </span>
                        <span className={`text-sm leading-relaxed ${dm ? 'text-slate-300' : 'text-slate-700'}`}>{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>

          {/* 8. TAN Correction Process */}
          <div id="correction" className="scroll-mt-24">
            <h2 className={`text-2xl font-extrabold mb-6 ${dm ? 'text-white' : 'text-slate-900'}`}>TAN Correction Process</h2>
            <div className={`space-y-4 text-base leading-relaxed mb-6 ${dm ? 'text-slate-300' : 'text-slate-600'}`}>
              <p>
                A TAN's core allotment never changes, but the details attached to it — <strong className={dm ? 'text-white' : 'text-slate-900'}>name, address, applicant category, contact details, the responsible person, and PAN linking</strong> — can and often do change as a business grows, restructures, or relocates. These corrections are filed through a TAN Change Request Form on the same NSDL/UTIITSL portal used for fresh applications, rather than through a fresh TAN application.
              </p>
              <p>
                The correction carries the same <strong className={dm ? 'text-white' : 'text-slate-900'}>₹77 fee</strong> as a new application and is typically processed within <strong className={dm ? 'text-white' : 'text-slate-900'}>7–10 working days</strong>. Keeping these details current matters more than it might seem — an outdated address or a responsible person who has since left the organisation can delay important department correspondence, including notices about pending TDS return discrepancies.
              </p>
            </div>
          </div>

          {/* 9. TDS/TCS Obligations After TAN */}
          <div id="obligations" className="scroll-mt-24">
            <h2 className={`text-2xl font-extrabold mb-2 ${dm ? 'text-white' : 'text-slate-900'}`}>TDS/TCS Obligations After TAN Allotment</h2>
            <p className={`text-sm leading-relaxed mb-6 ${dm ? 'text-slate-400' : 'text-slate-600'}`}>
              Getting the TAN is only the starting point — the recurring work is deducting the right amount, at the right rate, and depositing it on time under whichever section applies to each payment.
            </p>
            <DataTable headers={['Section', 'Nature of Payment', 'TDS/TCS Rate', 'Threshold']} rows={tdsObligationRows} dm={dm} />
            <p className={`text-xs leading-relaxed mt-3 ${dm ? 'text-slate-500' : 'text-slate-500'}`}>
              *Tax deducted or collected in any month must generally be deposited by the <strong className={dm ? 'text-slate-300' : 'text-slate-700'}>7th of the following month</strong> — the sole exception being deductions made in March, which must be deposited by <strong className={dm ? 'text-slate-300' : 'text-slate-700'}>30 April</strong> of the same year.
            </p>
          </div>

          {/* 10. Penalties for Non-Compliance */}
          <div id="penalties" className="scroll-mt-24">
            <h2 className={`text-2xl font-extrabold mb-2 ${dm ? 'text-white' : 'text-slate-900'}`}>Penalties for Non-Compliance</h2>
            <p className={`text-sm leading-relaxed mb-6 ${dm ? 'text-slate-400' : 'text-slate-600'}`}>
              TAN-related defaults are treated as strict-liability matters — the penalty applies regardless of whether the lapse was deliberate or an oversight.
            </p>
            <DataTable headers={['Non-Compliance', 'Provision', 'Consequence']} rows={penaltyRows} dm={dm} />
          </div>

          {/* 11. Benefits of Timely Registration */}
          <div id="benefits" className="scroll-mt-24">
            <h2 className={`text-2xl font-extrabold mb-6 ${dm ? 'text-white' : 'text-slate-900'}`}>Benefits of Timely TAN Registration</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {benefitCards.map((b) => (
                <div key={b.title} className={`rounded-2xl border p-5 ${dm ? 'border-slate-800 bg-slate-900/40' : 'border-slate-200 bg-white'}`}>
                  <div className="flex items-start gap-3">
                    <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-orange-500/10 text-brand-orange">
                      <CheckIcon className="h-4 w-4" />
                    </span>
                    <div>
                      <h3 className={`text-sm font-bold mb-1.5 ${dm ? 'text-white' : 'text-slate-900'}`}>{b.title}</h3>
                      <p className={`text-sm leading-relaxed ${dm ? 'text-slate-400' : 'text-slate-600'}`}>{b.desc}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* 12. FAQs */}
          <div id="faq" className="scroll-mt-24">
            <h2 className={`text-2xl font-extrabold mb-6 ${dm ? 'text-white' : 'text-slate-900'}`}>Frequently Asked Questions</h2>
            <div className="space-y-4">
              {faqs.map((faq, i) => (
                <div key={i} className={`rounded-2xl border overflow-hidden transition-colors ${dm ? 'border-slate-800 bg-slate-900/40 hover:bg-slate-900/70' : 'border-slate-200 bg-white hover:bg-slate-50'}`}>
                  <button
                    onClick={() => setActiveFaq(activeFaq === i ? null : i)}
                    className="w-full flex items-center justify-between p-6 text-left"
                  >
                    <span className={`font-semibold text-base pr-4 ${dm ? 'text-white' : 'text-slate-900'}`}>{faq.q}</span>
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="2.5" stroke="currentColor" className={`h-5 w-5 shrink-0 text-brand-orange transition-transform duration-200 ${activeFaq === i ? 'rotate-180' : ''}`}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
                    </svg>
                  </button>
                  {activeFaq === i && (
                    <div className={`px-6 pb-6 text-sm leading-relaxed ${dm ? 'text-slate-300' : 'text-slate-600'}`}>
                      {faq.a}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

        </div>

        {/* Sidebar */}
        <div className="lg:col-span-4">
          <div className="sticky top-24 space-y-6">
            <div className={`rounded-2xl border p-6 ${dm ? 'border-slate-800 bg-slate-900/40' : 'border-slate-200 bg-slate-50'}`}>
              <h3 className={`text-lg font-bold mb-4 ${dm ? 'text-white' : 'text-slate-900'}`}>Need Help?</h3>
              <p className={`text-sm leading-relaxed mb-6 ${dm ? 'text-slate-400' : 'text-slate-600'}`}>
                Have questions about TAN registration for your business? Let our experts help you figure out the right compliance approach.
              </p>
              <a href="#" onClick={(e) => { e.preventDefault(); setIsModalOpen(true); }} className={`w-full flex items-center justify-center gap-2 rounded-xl py-3 text-sm font-semibold transition-all ${dm ? 'bg-slate-800 text-white hover:bg-slate-700' : 'bg-white border border-slate-300 text-slate-700 hover:bg-slate-100'}`}>
                Contact Support
              </a>
            </div>
          </div>
        </div>
      </div>

      <Footer isDarkMode={dm} />

      <Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)}>
        <PopupForm
          serviceName="TAN Registration"
          onClose={() => setIsModalOpen(false)}
        />
      </Modal>
    </div>
  );
}
